package main

const TIMEOUT_RESPONSE="TIMEOUT\n"
const CONNECTION_ERROR_RESPONSE="CONNERROR\n"
const ANALYSIS_EXISTS_RESPONSE="ANALYSISEXISTS\n"
const INVALID_SERVER_RESPONSE="INVALIDSERVERRESPONSE\n"
const SUCCESS_RESPONSE="OK\n"
