FROM golang:alpine
RUN apk add git && go get github.com/streadway/amqp
WORKDIR /app
COPY *.go /app/
COPY data/* /app/data/

CMD sleep 10 && go run middleware.go streamer.go && sleep 20 && go run middleware.go collector.go
