FROM golang:alpine
RUN apk add git && go get github.com/streadway/amqp
WORKDIR /app
COPY *.go /app/
COPY data/atp_players.csv /app/data/atp_players.csv

CMD sleep 5 && go run middleware.go businesslogic.go worker.go -- demux:5 join:5 distribute_hands:1 distribute_surface:1 hands_processor:1 surface_processor:1 age_filter:8
